/**
 * Forge SDLC - Universal Generic Capability Catalog
 * Complete specification of all SDLC capabilities and provider bindings
 */

import { CapabilityManifest } from '../types/capability.js';

export const CAPABILITY_CATALOG: CapabilityManifest[] = [
  // ==========================================
  // 1. DISCOVERY GROUP
  // ==========================================
  {
    id: 'forge.brainstorm',
    name: 'brainstorm',
    displayName: 'Brainstorm & Ideation',
    group: 'discovery',
    description: 'Explore problem space, generate innovative feature ideas, and evaluate feasibility options.',
    version: '1.0.0',
    order: 1,
    tags: ['ideation', 'exploration', 'features', 'innovation'],
    inputs: [
      { name: 'problem_statement', type: 'user_input', required: true, description: 'Initial vision, problem statement or business objective' },
      { name: 'constraints', type: 'user_input', required: false, description: 'Technical, time or budgetary constraints' },
    ],
    outputs: [
      { name: 'brainstorm_report', type: 'artifact', artifactName: 'brainstorm.md', description: 'Structured brainstorming report with prioritized ideas', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Ideation Engine',
        nativeCapabilityId: 'bmad-brainstorm',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Deep lateral thinking techniques', 'Multi-perspective idea expansion', 'Strong feasibility ranking'],
        weaknesses: ['Can generate overly extensive idea trees if unconstrained'],
        bestFor: ['Open-ended product exploration', 'Greenfield projects', 'Innovation sprints'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Discovery',
        nativeCapabilityId: 'speckit-discover',
        specializationScore: 65,
        qualityScore: 75,
        strengths: ['Tight scoping to actionable items'],
        weaknesses: ['Limited creative exploration compared to BMAD'],
        bestFor: ['Fast feature scoping'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal Ideation',
        nativeCapabilityId: 'internal-brainstorm',
        specializationScore: 80,
        qualityScore: 85,
        strengths: ['Structured heuristics', 'Fast execution'],
        weaknesses: ['Standard heuristic prompting'],
        bestFor: ['Quick standard feature brainstorms'],
      },
    ],
  },
  {
    id: 'forge.discover',
    name: 'discover',
    displayName: 'Domain & Context Discovery',
    group: 'discovery',
    description: 'Discover existing system capabilities, dependencies, user personas, and domain boundaries.',
    version: '1.0.0',
    order: 2,
    tags: ['discovery', 'domain-analysis', 'context', 'personas'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: false, description: 'Existing repository or documentation' },
      { name: 'user_goals', type: 'user_input', required: true, description: 'Target user goals and system scope' },
    ],
    outputs: [
      { name: 'discovery_report', type: 'artifact', artifactName: 'discovery.md', description: 'Domain context, actor definitions, and boundary map', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Discovery & Context Engine',
        nativeCapabilityId: 'bmad-discover',
        specializationScore: 94,
        qualityScore: 92,
        strengths: ['Comprehensive domain modeling', 'Deep context boundary mapping', 'Persona & workflow synthesis'],
        weaknesses: ['Verbose outputs for trivial apps'],
        bestFor: ['Complex domain discovery', 'Enterprise projects', 'Multi-stakeholder systems'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Clarify & Context',
        nativeCapabilityId: 'speckit-clarify-context',
        specializationScore: 78,
        qualityScore: 82,
        strengths: ['Fast artifact grounding', 'Direct mapping to specification'],
        weaknesses: ['Less deep in multi-agent domain modeling'],
        bestFor: ['Spec-first discovery'],
      },
    ],
  },
  {
    id: 'forge.business-requirements',
    name: 'business-requirements',
    displayName: 'Business Requirements & BRD Engineering',
    group: 'discovery',
    description: 'Formulate comprehensive Business Requirements Documents (brd.md), stakeholder analysis, ROI models, business process flows, and value metrics.',
    version: '1.0.0',
    order: 3,
    tags: ['brd', 'business-requirements', 'stakeholders', 'roi', 'kpi', 'business-analysis', 'business-process', 'value-stream'],
    inputs: [
      { name: 'problem_statement', type: 'user_input', required: true, description: 'Executive vision, market opportunity, or business pain point' },
      { name: 'stakeholder_goals', type: 'user_input', required: false, description: 'Business stakeholder priorities and success criteria' },
    ],
    outputs: [
      { name: 'business_requirements_doc', type: 'artifact', artifactName: 'brd.md', description: 'Comprehensive Business Requirements Document (brd.md) with ROI, BPMN workflows, and scope', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Business Domain & Value Strategist',
        nativeCapabilityId: 'bmad-business-analysis',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['Deep stakeholder persona modeling', 'Business process workflow synthesis (BPMN / Mermaid)', 'Value proposition & ROI impact scoring', 'Clear In-Scope vs Out-of-Scope boundary definitions'],
        weaknesses: ['Can produce extensive narrative for simple internal scripts'],
        bestFor: ['Enterprise business cases', 'SaaS products', 'Multi-department digital transformation'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Business Scope Engine',
        nativeCapabilityId: 'speckit-business-scope',
        specializationScore: 89,
        qualityScore: 90,
        strengths: ['Tight MoSCoW prioritization', 'Traceability linking business goals directly to spec.md'],
        weaknesses: ['Focuses more on technical functional scope than market/ROI economics'],
        bestFor: ['Fast feature business scoping'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal BRD Synthesizer',
        nativeCapabilityId: 'internal-brd',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Standard IEEE/ISO compliant BRD structure', 'Fast executive summaries'],
        weaknesses: ['Standard heuristic templates'],
        bestFor: ['Standard project business documents'],
      },
    ],
  },
  {
    id: 'forge.research',
    name: 'research',
    displayName: 'Technical Research & Spike',
    group: 'discovery',
    description: 'Investigate technical libraries, protocols, API integrations, benchmarks, and architectural precedents.',
    version: '1.0.0',
    order: 3,
    tags: ['research', 'spikes', 'benchmarks', 'evaluation'],
    inputs: [
      { name: 'research_questions', type: 'user_input', required: true, description: 'Technical questions or comparison targets' },
    ],
    outputs: [
      { name: 'research_report', type: 'artifact', artifactName: 'research.md', description: 'Technical comparison matrix, trade-offs, and spike findings', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Deep Research Spike',
        nativeCapabilityId: 'bmad-research',
        specializationScore: 92,
        qualityScore: 90,
        strengths: ['Multi-criteria trade-off tables', 'Deep package compatibility checks'],
        weaknesses: ['May suggest extensive architectural patterns'],
        bestFor: ['Complex library evaluations', 'AI system architectures'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal Spike Engine',
        nativeCapabilityId: 'internal-research',
        specializationScore: 85,
        qualityScore: 88,
        strengths: ['Focused, pragmatic recommendations', 'Fast synthesis'],
        weaknesses: ['Less specialized in niche domain spikes'],
        bestFor: ['Standard web/backend tech evaluations'],
      },
    ],
  },
  {
    id: 'forge.requirements',
    name: 'requirements',
    displayName: 'Requirements Engineering',
    group: 'discovery',
    description: 'Capture, categorize, and prioritize functional and non-functional requirements with traceability.',
    version: '1.0.0',
    order: 4,
    tags: ['requirements', 'user-stories', 'nfr', 'moscow'],
    inputs: [
      { name: 'discovery_report', type: 'artifact', required: false, defaultArtifact: 'discovery.md', description: 'Prior discovery findings' },
      { name: 'user_input', type: 'user_input', required: true, description: 'Feature goals and business rules' },
    ],
    outputs: [
      { name: 'requirements_doc', type: 'artifact', artifactName: 'requirements.md', description: 'Prioritized functional and non-functional requirements (MoSCoW)', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Requirements Engine',
        nativeCapabilityId: 'speckit-requirements',
        specializationScore: 93,
        qualityScore: 92,
        strengths: ['Rigorous requirement structure', 'Traceability to acceptance tests', 'Clean MoSCoW breakdown'],
        weaknesses: ['Requires structured inputs'],
        bestFor: ['Specification-driven engineering', 'Contract-first development'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Requirement Elicitation',
        nativeCapabilityId: 'bmad-elicitation',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Deep conversational elicitation', 'Edge-case unearthing'],
        weaknesses: ['Can be conversational before final artifact generation'],
        bestFor: ['Complex, ambiguous requirements'],
      },
    ],
  },
  {
    id: 'forge.clarify',
    name: 'clarify',
    displayName: 'Requirements Clarification & Ambiguity Elicitation',
    group: 'discovery',
    description: 'Interrogate ambiguous requirements, resolve edge cases, and eliminate hidden assumptions through structured Q&A.',
    version: '1.0.0',
    order: 5,
    tags: ['clarification', 'elicitation', 'ambiguity', 'edge-cases'],
    inputs: [
      { name: 'draft_requirements', type: 'artifact', required: false, defaultArtifact: 'requirements.md', description: 'Initial requirements or draft spec' },
      { name: 'user_input', type: 'user_input', required: true, description: 'Context and ambiguous scope' },
    ],
    outputs: [
      { name: 'clarification_log', type: 'artifact', artifactName: 'clarifications.md', description: 'Resolved ambiguities, answered questions, and edge-case decisions', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Advanced Elicitation',
        nativeCapabilityId: 'bmad-advanced-elicitation',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['Unrivaled deep questioning', 'Identifies hidden state machine gaps', 'Probes implicit architectural assumptions'],
        weaknesses: ['Generates multiple deep questions'],
        bestFor: ['Ambiguous or mission-critical projects', 'Complex enterprise state logic'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Clarify',
        nativeCapabilityId: 'speckit-clarify',
        specializationScore: 91,
        qualityScore: 90,
        strengths: ['Concise, structured Q&A tables', 'Direct spec integration', 'Focus on testable outcomes'],
        weaknesses: ['Less aggressive in unearthing implicit domain logic'],
        bestFor: ['Fast structured clarification', 'Standard spec pipelines'],
      },
    ],
  },

  // ==========================================
  // 2. SPECIFICATION GROUP
  // ==========================================
  {
    id: 'forge.constitution',
    name: 'constitution',
    displayName: 'Constitution & Principles',
    group: 'specification',
    description: 'Define core project principles, non-negotiable standards, architectural invariants, and governance rules.',
    version: '1.0.0',
    order: 6,
    tags: ['constitution', 'principles', 'standards', 'governance'],
    inputs: [
      { name: 'project_guidelines', type: 'user_input', required: false, description: 'Core principles, code philosophies, and security rules' },
    ],
    outputs: [
      { name: 'constitution_doc', type: 'artifact', artifactName: 'constitution.md', description: 'Governing project principles, non-negotiables, and engineering rules', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Constitution Engine',
        nativeCapabilityId: 'speckit-constitution',
        specializationScore: 98,
        qualityScore: 96,
        strengths: ['Native first-class constitution support', 'Enforceable invariant checks', 'SDD governance'],
        weaknesses: ['None in constitution domain'],
        bestFor: ['Spec Kit-aligned projects', 'Strict governance and team consistency'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Built-in Constitution',
        nativeCapabilityId: 'internal-constitution',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Security-first invariants', 'Clean modern software principles'],
        weaknesses: ['Standard templates'],
        bestFor: ['Quick standard project invariants'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Principles Customization',
        nativeCapabilityId: 'bmad-principles',
        specializationScore: 75,
        qualityScore: 80,
        strengths: ['Customizable prompt rules'],
        weaknesses: ['Constitution is not an isolated artifact in BMAD core'],
        bestFor: ['BMAD workflow customization'],
      },
    ],
  },
  {
    id: 'forge.specify',
    name: 'specify',
    displayName: 'Software Specification (SDD)',
    group: 'specification',
    description: 'Generate definitive, complete, testable software specification documents (spec.md) based on user stories and requirements.',
    version: '1.0.0',
    order: 7,
    tags: ['specification', 'sdd', 'spec', 'user-stories', 'scope'],
    inputs: [
      { name: 'constitution', type: 'artifact', required: false, defaultArtifact: 'constitution.md', description: 'Governing principles' },
      { name: 'clarifications', type: 'artifact', required: false, defaultArtifact: 'clarifications.md', description: 'Clarification decisions' },
      { name: 'user_requirements', type: 'user_input', required: true, description: 'Feature goals, user stories, and acceptance criteria' },
    ],
    outputs: [
      { name: 'specification_doc', type: 'artifact', artifactName: 'spec.md', description: 'Definitive functional specification (spec.md) with strict user stories and scenarios', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Specification (spec.md)',
        nativeCapabilityId: 'speckit-specify',
        specializationScore: 99,
        qualityScore: 97,
        strengths: ['Industry standard spec-driven format', 'Strict Given-When-Then scenarios', 'Traceable requirements', 'Built-in schema validation'],
        weaknesses: ['Strict format requires disciplined input'],
        bestFor: ['Spec-Driven Development', 'High-quality engineering specifications'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Planning & Story Spec',
        nativeCapabilityId: 'bmad-specification',
        specializationScore: 82,
        qualityScore: 86,
        strengths: ['Deep narrative descriptions', 'Rich user interaction flows'],
        weaknesses: ['Less standard format than Spec Kit SDD'],
        bestFor: ['Narrative product specs'],
      },
    ],
  },
  {
    id: 'forge.acceptance',
    name: 'acceptance',
    displayName: 'Acceptance Criteria & Scenarios',
    group: 'specification',
    description: 'Formulate exhaustive Gherkin/Cucumber acceptance criteria and boundary test matrices.',
    version: '1.0.0',
    order: 8,
    tags: ['acceptance', 'gherkin', 'bdd', 'scenarios'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Functional specification' },
    ],
    outputs: [
      { name: 'acceptance_criteria', type: 'artifact', artifactName: 'acceptance.md', description: 'Gherkin feature scenarios and acceptance criteria matrix', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Acceptance Generator',
        nativeCapabilityId: 'speckit-acceptance',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Given-When-Then consistency', 'Zero ambiguity', 'Direct mapping to test suites'],
        weaknesses: ['Can be terse'],
        bestFor: ['BDD test suites', 'Automated QA gates'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal BDD Generator',
        nativeCapabilityId: 'internal-acceptance',
        specializationScore: 84,
        qualityScore: 86,
        strengths: ['Standard Gherkin output'],
        weaknesses: ['Standard coverage'],
        bestFor: ['Fast criteria definition'],
      },
    ],
  },
  {
    id: 'forge.checklist',
    name: 'checklist',
    displayName: 'Quality & Completeness Checklist',
    group: 'specification',
    description: 'Generate verification checklists covering security, UX, performance, error states, and edge conditions.',
    version: '1.0.0',
    order: 9,
    tags: ['checklist', 'quality-gate', 'readiness', 'audit'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification document' },
      { name: 'constitution', type: 'artifact', required: false, defaultArtifact: 'constitution.md', description: 'Project constitution' },
    ],
    outputs: [
      { name: 'quality_checklist', type: 'artifact', artifactName: 'checklist.md', description: 'Exhaustive pre-implementation and pre-release checklist', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Checklist Engine',
        nativeCapabilityId: 'speckit-checklist',
        specializationScore: 97,
        qualityScore: 95,
        strengths: ['Native checklist methodology', 'Strict audit items', 'Categorized quality criteria'],
        weaknesses: ['Static unless re-run'],
        bestFor: ['Rigorous quality checks', 'Spec Kit compliance'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Review & Audit Checklist',
        nativeCapabilityId: 'bmad-checklist',
        specializationScore: 83,
        qualityScore: 86,
        strengths: ['Multi-perspective review points'],
        weaknesses: ['Less structured markdown checklist tables'],
        bestFor: ['Holistic review checklists'],
      },
    ],
  },

  // ==========================================
  // 3. ARCHITECTURE GROUP
  // ==========================================
  {
    id: 'forge.architecture',
    name: 'architecture',
    displayName: 'Technical Architecture & System Design',
    group: 'architecture',
    description: 'Design robust technical architecture, system components, data flows, technology choices, and trade-off analyses.',
    version: '1.0.0',
    order: 10,
    tags: ['architecture', 'system-design', 'components', 'c4-model', 'scalability'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification document' },
      { name: 'constitution', type: 'artifact', required: false, defaultArtifact: 'constitution.md', description: 'Project invariants' },
      { name: 'existing_codebase', type: 'codebase', required: false, description: 'Current codebase if brownfield' },
    ],
    outputs: [
      { name: 'architecture_doc', type: 'artifact', artifactName: 'architecture.md', description: 'Comprehensive system architecture, C4 diagrams, component boundaries, and design decisions', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Architecture & System Design',
        nativeCapabilityId: 'bmad-architecture',
        specializationScore: 97,
        qualityScore: 96,
        strengths: ['Specialized multi-tier architectural workflows', 'Deep pattern reasoning (Event-driven, Microservices, Hexagonal, Clean Arch)', 'Exhaustive trade-off matrices', 'Mermaid diagram generation'],
        weaknesses: ['Can be heavyweight for single-script CLI tools'],
        bestFor: ['Fullstack systems', 'Distributed systems', 'AI agent architectures', 'Scalable enterprise platforms'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Plan & Architecture',
        nativeCapabilityId: 'speckit-plan-arch',
        specializationScore: 76,
        qualityScore: 82,
        strengths: ['Tight coupling with plan.md and tasks.md', 'Pragmatic and directly actionable'],
        weaknesses: ['Less specialized in deep system architecture diagrams and distributed patterns'],
        bestFor: ['Fast monolithic apps', 'Simple CRUD or CLI tools'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal Architecture Engine',
        nativeCapabilityId: 'internal-architecture',
        specializationScore: 88,
        qualityScore: 90,
        strengths: ['Clean modular patterns', 'TypeScript/Node/Fullstack best practices', 'Built-in security considerations'],
        weaknesses: ['Standardized architecture heuristics'],
        bestFor: ['Modern web/API services and CLI packages'],
      },
    ],
  },
  {
    id: 'forge.system-design',
    name: 'system-design',
    displayName: 'High-Level System Design & Topology',
    group: 'architecture',
    description: 'Map high-level service topologies, communication protocols, caching strategies, and resilience patterns.',
    version: '1.0.0',
    order: 11,
    tags: ['system-design', 'topology', 'caching', 'microservices'],
    inputs: [
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
    ],
    outputs: [
      { name: 'system_design_doc', type: 'artifact', artifactName: 'system-design.md', description: 'System topology, caching, rate limiting, and network diagrams', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD System Topology Engine',
        nativeCapabilityId: 'bmad-system-design',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Deep resilience patterns (circuit breakers, retry queues)', 'Network & infrastructure topology mapping'],
        weaknesses: ['Extensive design output'],
        bestFor: ['Cloud native systems', 'Distributed microservices'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal System Design',
        nativeCapabilityId: 'internal-system-design',
        specializationScore: 85,
        qualityScore: 87,
        strengths: ['Clear serverless/container patterns'],
        weaknesses: ['Standard patterns'],
        bestFor: ['Standard web applications'],
      },
    ],
  },
  {
    id: 'forge.data-model',
    name: 'data-model',
    displayName: 'Data Modeling & Schema Design',
    group: 'architecture',
    description: 'Design normalized/denormalized database schemas, migrations, ER diagrams, entity relationships, and indexing strategies.',
    version: '1.0.0',
    order: 12,
    tags: ['data-model', 'database', 'schema', 'sql', 'nosql', 'prisma', 'postgres'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification doc' },
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
    ],
    outputs: [
      { name: 'data_model_doc', type: 'artifact', artifactName: 'data-model.md', description: 'Entity-relationship diagrams, schema definitions (Prisma/SQL/JSON-Schema), and indexing rules', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Data & Entity Modeler',
        nativeCapabilityId: 'bmad-data-model',
        specializationScore: 94,
        qualityScore: 93,
        strengths: ['Deep relational modeling', 'Indexing strategies', 'State-machine modeling', 'Mermaid ERD generation'],
        weaknesses: ['Can over-normalize if not instructed'],
        bestFor: ['Complex relational or document databases', 'Event store schemas'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Schema & Entity Modeler',
        nativeCapabilityId: 'internal-data-model',
        specializationScore: 88,
        qualityScore: 90,
        strengths: ['Generates ready-to-use Prisma/Zod/TypeScript interfaces', 'Pragmatic indexing'],
        weaknesses: ['Less specialized in niche graph/time-series databases'],
        bestFor: ['TypeScript / SQL / MongoDB schemas'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Plan Data Entities',
        nativeCapabilityId: 'speckit-data-entities',
        specializationScore: 72,
        qualityScore: 78,
        strengths: ['Clean entity definitions in plan.md'],
        weaknesses: ['Data modeling is embedded in general plan, not an isolated deep schema artifact'],
        bestFor: ['Lightweight schema design in plan'],
      },
    ],
  },
  {
    id: 'forge.api-design',
    name: 'api-design',
    displayName: 'API Contracts & Interface Design',
    group: 'architecture',
    description: 'Design OpenAPI 3.1 / GraphQL / gRPC contracts, request/response schemas, error codes, and authentication flows.',
    version: '1.0.0',
    order: 13,
    tags: ['api-design', 'openapi', 'rest', 'graphql', 'grpc', 'api-contract'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification doc' },
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
    ],
    outputs: [
      { name: 'api_contract_doc', type: 'artifact', artifactName: 'api-contract.md', description: 'Formal OpenAPI 3.1 schema, endpoint contracts, error envelopes, and idempotency rules', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD API Contract Designer',
        nativeCapabilityId: 'bmad-api-design',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Exhaustive error handling contracts', 'Pagination & idempotency design', 'REST/GraphQL/gRPC support'],
        weaknesses: ['Verbose schema specifications'],
        bestFor: ['Microservice APIs', 'Public Developer APIs', 'SaaS backends'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal API Generator',
        nativeCapabilityId: 'internal-api-design',
        specializationScore: 90,
        qualityScore: 91,
        strengths: ['OpenAPI 3.1 compliant YAML/JSON output', 'TypeScript route types generation'],
        weaknesses: ['Standard REST patterns'],
        bestFor: ['Fast REST / RPC API definitions'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Plan API Contracts',
        nativeCapabilityId: 'speckit-plan-api',
        specializationScore: 74,
        qualityScore: 80,
        strengths: ['Functional endpoint mapping'],
        weaknesses: ['Embedded in plan.md rather than standalone OpenAPI specs'],
        bestFor: ['Simple endpoint lists'],
      },
    ],
  },
  {
    id: 'forge.security-design',
    name: 'security-design',
    displayName: 'Security Architecture & Threat Modeling',
    group: 'architecture',
    description: 'STRIDE threat modeling, authentication/authorization architecture (RBAC/ABAC/OAuth/JWT), and encryption standards.',
    version: '1.0.0',
    order: 14,
    tags: ['security-design', 'stride', 'threat-model', 'oauth', 'jwt', 'encryption'],
    inputs: [
      { name: 'architecture', type: 'artifact', required: true, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
    ],
    outputs: [
      { name: 'threat_model_doc', type: 'artifact', artifactName: 'threat-model.md', description: 'STRIDE threat model, mitigation strategies, security boundary diagrams, and cryptographic standards', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Security Invariant Engine',
        nativeCapabilityId: 'internal-security-design',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['STRIDE matrix generation', 'OWASP Top 10 mitigation mapping', 'Strict auth & encryption rules', 'Zero-trust architecture checklists'],
        weaknesses: ['Requires architecture.md for best results'],
        bestFor: ['Security-critical systems', 'Fintech', 'Auth pipelines'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Security & Threat Modeling',
        nativeCapabilityId: 'bmad-security-design',
        specializationScore: 91,
        qualityScore: 90,
        strengths: ['Systematic vulnerability scenario mapping'],
        weaknesses: ['Less standard OWASP compliance reporting than Forge Internal'],
        bestFor: ['Complex system threat models'],
      },
    ],
  },
  {
    id: 'forge.ai-architecture',
    name: 'ai-architecture',
    displayName: 'AI & Agentic Architecture',
    group: 'architecture',
    description: 'Design LLM agent workflows, prompt routing, tool schemas, context window management, and RAG pipelines.',
    version: '1.0.0',
    order: 15,
    tags: ['ai-architecture', 'llm', 'rag', 'agents', 'vector-db', 'prompt-engineering'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification doc' },
    ],
    outputs: [
      { name: 'ai_architecture_doc', type: 'artifact', artifactName: 'ai-architecture.md', description: 'Agentic state machine, memory architecture, tool call schemas, and fallback strategies', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Multi-Agent Architect',
        nativeCapabilityId: 'bmad-ai-architecture',
        specializationScore: 98,
        qualityScore: 96,
        strengths: ['Pioneering multi-agent interaction topologies', 'Context management strategies', 'Autonomous tool calling designs'],
        weaknesses: ['Can be sophisticated for simple LLM wrapper apps'],
        bestFor: ['Agentic platforms', 'Complex autonomous workflows', 'Multi-agent orchestration'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal AI Architecture',
        nativeCapabilityId: 'internal-ai-arch',
        specializationScore: 89,
        qualityScore: 91,
        strengths: ['Standard RAG pipelines', 'Deterministic fallback patterns', 'LangChain/LlamaIndex integration models'],
        weaknesses: ['Less specialized in multi-agent swarms'],
        bestFor: ['RAG search apps and Copilot assistants'],
      },
    ],
  },
  {
    id: 'forge.infrastructure-design',
    name: 'infrastructure-design',
    displayName: 'Infrastructure & Cloud Architecture',
    group: 'architecture',
    description: 'Design cloud infrastructure, Terraform / CDK specs, Kubernetes manifests, CI/CD topology, and observability.',
    version: '1.0.0',
    order: 16,
    tags: ['infrastructure', 'terraform', 'aws', 'gcp', 'kubernetes', 'docker', 'cicd'],
    inputs: [
      { name: 'architecture', type: 'artifact', required: true, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
    ],
    outputs: [
      { name: 'infra_design_doc', type: 'artifact', artifactName: 'infrastructure.md', description: 'Cloud infrastructure topologies, IaC templates, Docker setups, and deployment matrices', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge DevOps & Cloud Engine',
        nativeCapabilityId: 'internal-infra',
        specializationScore: 94,
        qualityScore: 93,
        strengths: ['Docker multi-stage builds', 'GitHub Actions workflows', 'Terraform/CloudFormation templates', 'Cost optimization heuristics'],
        weaknesses: ['Standard cloud architectures'],
        bestFor: ['Cloud deployments', 'CI/CD pipeline architecture'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Infrastructure Blueprint',
        nativeCapabilityId: 'bmad-infra',
        specializationScore: 84,
        qualityScore: 86,
        strengths: ['Architecture-to-infra mapping'],
        weaknesses: ['Less template-driven than Forge Internal'],
        bestFor: ['High-level cloud mapping'],
      },
    ],
  },

  // ==========================================
  // 4. PLANNING GROUP
  // ==========================================
  {
    id: 'forge.plan',
    name: 'plan',
    displayName: 'Technical Execution Plan',
    group: 'planning',
    description: 'Synthesize specification and architecture into phased technical milestones, dependency graphs, and execution roadmaps.',
    version: '1.0.0',
    order: 17,
    tags: ['plan', 'technical-plan', 'milestones', 'roadmap', 'phases'],
    inputs: [
      { name: 'specification', type: 'artifact', required: true, defaultArtifact: 'spec.md', description: 'Specification doc' },
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
      { name: 'constitution', type: 'artifact', required: false, defaultArtifact: 'constitution.md', description: 'Project constitution' },
    ],
    outputs: [
      { name: 'plan_doc', type: 'artifact', artifactName: 'plan.md', description: 'Structured execution plan (plan.md) with phase milestones, risk mitigations, and technology choices', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Technical Plan (plan.md)',
        nativeCapabilityId: 'speckit-plan',
        specializationScore: 97,
        qualityScore: 96,
        strengths: ['Flawless integration with spec.md and tasks.md', 'SDD phase definitions', 'Clear input/output contracts per milestone'],
        weaknesses: ['Assumes Spec Kit artifact conventions'],
        bestFor: ['Structured feature implementations', 'Spec-driven execution'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Strategic Planning Engine',
        nativeCapabilityId: 'bmad-plan',
        specializationScore: 91,
        qualityScore: 92,
        strengths: ['Deep critical path analysis', 'Comprehensive risk mitigation tables', 'Architectural milestone alignment'],
        weaknesses: ['Output can be more narrative than Spec Kit plan.md'],
        bestFor: ['Large refactors', 'Complex systems engineering'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Agile Milestone Planner',
        nativeCapabilityId: 'internal-plan',
        specializationScore: 86,
        qualityScore: 88,
        strengths: ['Pragmatic sprint and milestone breakdown'],
        weaknesses: ['Standard planning heuristics'],
        bestFor: ['Standard feature releases'],
      },
    ],
  },
  {
    id: 'forge.task-decomposition',
    name: 'tasks',
    displayName: 'Task Decomposition & Work Breakdown',
    group: 'planning',
    description: 'Decompose technical plan into granular, atomic, testable developer tasks (tasks.md) with strict dependencies and file targets.',
    version: '1.0.0',
    order: 18,
    tags: ['tasks', 'task-decomposition', 'wbs', 'atomic-tasks', 'actionable'],
    inputs: [
      { name: 'plan', type: 'artifact', required: true, defaultArtifact: 'plan.md', description: 'Technical plan' },
      { name: 'specification', type: 'artifact', required: false, defaultArtifact: 'spec.md', description: 'Specification doc' },
    ],
    outputs: [
      { name: 'tasks_doc', type: 'artifact', artifactName: 'tasks.md', description: 'Actionable developer task checklist (tasks.md) with acceptance criteria per task and file paths', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Tasks Breakdown (tasks.md)',
        nativeCapabilityId: 'speckit-tasks',
        specializationScore: 98,
        qualityScore: 97,
        strengths: ['Industry-leading task atomicity', 'Every task targets explicit files and test assertions', 'Directly executable by AI coding agents', 'Interactive checklist syntax'],
        weaknesses: ['None in task decomposition'],
        bestFor: ['Agentic coding execution', 'Step-by-step developer tasks'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Workflow Task Decomposition',
        nativeCapabilityId: 'bmad-tasks',
        specializationScore: 85,
        qualityScore: 88,
        strengths: ['Excellent thematic task grouping'],
        weaknesses: ['Less standardized markdown task syntax than Spec Kit'],
        bestFor: ['High-level milestone tasks'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal Task Engine',
        nativeCapabilityId: 'internal-tasks',
        specializationScore: 89,
        qualityScore: 90,
        strengths: ['Explicit file-by-file action items', 'Built-in verification step per task'],
        weaknesses: ['Standard heuristics'],
        bestFor: ['Targeted refactoring tasks'],
      },
    ],
  },
  {
    id: 'forge.estimate',
    name: 'estimate',
    displayName: 'Effort Estimation & Complexity Analysis',
    group: 'planning',
    description: 'Calculate complexity scores, story points, risks, and agent execution times per task.',
    version: '1.0.0',
    order: 19,
    tags: ['estimate', 'complexity', 'story-points', 'sizing'],
    inputs: [
      { name: 'tasks', type: 'artifact', required: true, defaultArtifact: 'tasks.md', description: 'Tasks breakdown' },
    ],
    outputs: [
      { name: 'estimates_doc', type: 'artifact', artifactName: 'estimates.md', description: 'Complexity matrix, risk scores, and estimated execution hours/tokens', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Complexity & Estimator',
        nativeCapabilityId: 'internal-estimate',
        specializationScore: 92,
        qualityScore: 90,
        strengths: ['Algorithmic complexity heuristic', 'Token and time estimations', 'High-risk task flagging'],
        weaknesses: ['Based on heuristic models'],
        bestFor: ['Project sizing and sprint planning'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Risk & Sizing Analysis',
        nativeCapabilityId: 'bmad-estimate',
        specializationScore: 86,
        qualityScore: 87,
        strengths: ['Risk-weighted sizing'],
        weaknesses: ['Qualitative sizing'],
        bestFor: ['Architectural risk assessment'],
      },
    ],
  },
  {
    id: 'forge.dependency-analysis',
    name: 'dependency-analysis',
    displayName: 'Dependency & Critical Path Analysis',
    group: 'planning',
    description: 'Map task dependencies, identify circular dependencies, detect blocking paths, and optimize parallel execution tracks.',
    version: '1.0.0',
    order: 20,
    tags: ['dependency-analysis', 'dag', 'critical-path', 'parallelism'],
    inputs: [
      { name: 'tasks', type: 'artifact', required: true, defaultArtifact: 'tasks.md', description: 'Tasks breakdown' },
    ],
    outputs: [
      { name: 'dependency_doc', type: 'artifact', artifactName: 'dependency-graph.md', description: 'DAG representation of tasks, parallel workstreams, and critical path analysis', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Dependency Analyzer',
        nativeCapabilityId: 'speckit-dependencies',
        specializationScore: 92,
        qualityScore: 91,
        strengths: ['Strict topological sorting of tasks.md', 'Parallel agent dispatch preparation'],
        weaknesses: ['Requires well-structured tasks.md'],
        bestFor: ['Multi-agent parallel execution'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge DAG Engine',
        nativeCapabilityId: 'internal-dag',
        specializationScore: 90,
        qualityScore: 90,
        strengths: ['Mermaid DAG diagram generation', 'Parallel execution tracks'],
        weaknesses: ['Standard DAG algorithms'],
        bestFor: ['Visualizing task workflows'],
      },
    ],
  },

  // ==========================================
  // 5. IMPLEMENTATION GROUP
  // ==========================================
  {
    id: 'forge.implement',
    name: 'implement',
    displayName: 'Agentic Code Implementation',
    group: 'implementation',
    description: 'Execute developer tasks into clean, idiomatic, typed source code strictly adhering to spec, architecture, and constitution.',
    version: '1.0.0',
    order: 21,
    tags: ['implement', 'code-generation', 'agentic-coding', 'development', 'tdd'],
    inputs: [
      { name: 'tasks', type: 'artifact', required: true, defaultArtifact: 'tasks.md', description: 'Tasks breakdown' },
      { name: 'spec', type: 'artifact', required: false, defaultArtifact: 'spec.md', description: 'Specification doc' },
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Architecture doc' },
      { name: 'existing_codebase', type: 'codebase', required: false, description: 'Workspace code' },
    ],
    outputs: [
      { name: 'source_code', type: 'code', description: 'Implemented production source files, tests, and configurations', format: 'source_code' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Agentic Developer',
        nativeCapabilityId: 'bmad-implement',
        specializationScore: 93,
        qualityScore: 94,
        strengths: ['Deep context awareness', 'Strong adherence to complex architecture patterns', 'Sophisticated multi-file coordination'],
        weaknesses: ['Can produce larger code edits in single passes'],
        bestFor: ['Complex domain code', 'Fullstack multi-layer features', 'Pattern-heavy code'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Task Implementer',
        nativeCapabilityId: 'speckit-implement',
        specializationScore: 92,
        qualityScore: 93,
        strengths: ['Atomic task-by-task execution', 'Strict verification against spec criteria', 'Minimal code churn'],
        weaknesses: ['Prefers strict tasks.md input'],
        bestFor: ['TDD workflows', 'Spec-driven implementation'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Direct Code Synthesizer',
        nativeCapabilityId: 'internal-implement',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Fast execution', 'Idiomatic TypeScript/Node/React/Python boilerplate'],
        weaknesses: ['Standard agent implementation'],
        bestFor: ['Utility creation and quick prototypes'],
      },
    ],
  },
  {
    id: 'forge.refactor',
    name: 'refactor',
    displayName: 'Code Refactoring & Technical Debt Cleanup',
    group: 'implementation',
    description: 'Clean up code smells, modularize monolithic components, improve maintainability without altering external behavior.',
    version: '1.0.0',
    order: 22,
    tags: ['refactor', 'clean-code', 'modularity', 'tech-debt', 'solid'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Code to refactor' },
      { name: 'architecture', type: 'artifact', required: false, defaultArtifact: 'architecture.md', description: 'Target architecture' },
    ],
    outputs: [
      { name: 'refactored_code', type: 'code', description: 'Cleaned, refactored source code', format: 'source_code' },
      { name: 'refactor_summary', type: 'artifact', artifactName: 'refactor-summary.md', description: 'Summary of transformations, code smell resolutions, and metrics', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Deep Refactoring Engine',
        nativeCapabilityId: 'bmad-refactor',
        specializationScore: 95,
        qualityScore: 93,
        strengths: ['Extracts clean domain boundaries', 'Applies SOLID design patterns', 'Safe multi-stage refactoring plans'],
        weaknesses: ['Requires test suite for safe large transformations'],
        bestFor: ['Monolith decoupling', 'Legacy codebase modernization'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Clean Code Refactorer',
        nativeCapabilityId: 'internal-refactor',
        specializationScore: 87,
        qualityScore: 88,
        strengths: ['Functions modularization', 'TypeScript strict type fixing', 'ESM modernization'],
        weaknesses: ['Standard refactoring heuristics'],
        bestFor: ['Module-level cleanup and type tightening'],
      },
    ],
  },
  {
    id: 'forge.migrate',
    name: 'migrate',
    displayName: 'Migration & Framework Upgrades',
    group: 'implementation',
    description: 'Migrate legacy APIs, upgrade library versions, port from JavaScript to TypeScript, or transition frameworks.',
    version: '1.0.0',
    order: 23,
    tags: ['migrate', 'upgrade', 'porting', 'framework-migration'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Source code to migrate' },
      { name: 'migration_target', type: 'user_input', required: true, description: 'Target library/version/framework' },
    ],
    outputs: [
      { name: 'migrated_code', type: 'code', description: 'Migrated code files and updated package manifests', format: 'source_code' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Migration Specialist',
        nativeCapabilityId: 'internal-migrate',
        specializationScore: 92,
        qualityScore: 91,
        strengths: ['Automated codemods', 'Dependency version conflict resolution', 'Breaking change mitigation'],
        weaknesses: ['Needs target version specifications'],
        bestFor: ['JS to TS conversions', 'Major dependency version upgrades'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Legacy Modernizer',
        nativeCapabilityId: 'bmad-migrate',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Holistic architectural migrations'],
        weaknesses: ['More verbose transformation steps'],
        bestFor: ['Full architectural transitions'],
      },
    ],
  },
  {
    id: 'forge.fix',
    name: 'fix',
    displayName: 'Bug Diagnosis & Root Cause Fix',
    group: 'implementation',
    description: 'Diagnose runtime errors, stack traces, race conditions, or broken tests, and generate surgical bug fixes with regression tests.',
    version: '1.0.0',
    order: 24,
    tags: ['fix', 'bug-fix', 'debugging', 'root-cause', 'regression-test'],
    inputs: [
      { name: 'error_log', type: 'user_input', required: true, description: 'Stack trace, error message, or bug description' },
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Codebase' },
    ],
    outputs: [
      { name: 'fixed_code', type: 'code', description: 'Surgically patched code and reproduction regression test', format: 'source_code' },
      { name: 'root_cause_report', type: 'artifact', artifactName: 'bugfix-report.md', description: 'Root cause analysis and prevention measures', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Root-Cause Debugger',
        nativeCapabilityId: 'internal-fix',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Surgical, minimal diffs', 'Automatic regression test generation', 'Deep stack trace dissection'],
        weaknesses: ['Requires clear error context'],
        bestFor: ['Runtime exceptions', 'Test failures', 'Logic bugs'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Multi-Lens Diagnostics',
        nativeCapabilityId: 'bmad-fix',
        specializationScore: 90,
        qualityScore: 91,
        strengths: ['Examines systemic root causes across layers'],
        weaknesses: ['Can suggest wider refactoring than a single bug fix'],
        bestFor: ['Complex state-synchronization or race bugs'],
      },
    ],
  },

  // ==========================================
  // 6. VERIFICATION GROUP
  // ==========================================
  {
    id: 'forge.test',
    name: 'test',
    displayName: 'Test Suite Generation & Automation',
    group: 'verification',
    description: 'Generate comprehensive unit, integration, edge-case, and end-to-end test suites verifying all acceptance scenarios.',
    version: '1.0.0',
    order: 25,
    tags: ['test', 'unit-test', 'integration-test', 'e2e', 'vitest', 'jest', 'playwright', 'coverage'],
    inputs: [
      { name: 'specification', type: 'artifact', required: false, defaultArtifact: 'spec.md', description: 'Specification doc' },
      { name: 'acceptance', type: 'artifact', required: false, defaultArtifact: 'acceptance.md', description: 'Acceptance scenarios' },
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Implemented source code' },
    ],
    outputs: [
      { name: 'test_files', type: 'code', description: 'Executable test files and fixtures', format: 'source_code' },
      { name: 'test_report', type: 'artifact', artifactName: 'test-report.md', description: 'Test coverage and verification report', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Test Automation Suite',
        nativeCapabilityId: 'internal-test',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['Generates runnable Vitest / Jest / PyTest suites', 'Exhaustive edge-case mocking', 'Coverage-driven test synthesis', 'Zero flaky test patterns'],
        weaknesses: ['None in standard test suites'],
        bestFor: ['Unit & Integration tests', 'API endpoint testing', 'TDD automation'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Acceptance Test Runner',
        nativeCapabilityId: 'speckit-test',
        specializationScore: 89,
        qualityScore: 90,
        strengths: ['Direct Gherkin to test scenario translation'],
        weaknesses: ['Focuses on acceptance tests rather than internal unit mocks'],
        bestFor: ['Acceptance criteria validation'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Multi-Perspective Test Designer',
        nativeCapabilityId: 'bmad-test',
        specializationScore: 87,
        qualityScore: 89,
        strengths: ['Fault-injection and chaos test ideas'],
        weaknesses: ['Less standard runner integration'],
        bestFor: ['Resilience and boundary testing'],
      },
    ],
  },
  {
    id: 'forge.analyze',
    name: 'analyze',
    displayName: 'Cross-Artifact Consistency Analysis',
    group: 'verification',
    description: 'Perform deep semantic audit across artifacts (constitution -> spec -> architecture -> plan -> tasks -> code) to detect drift, gaps, or contradictions.',
    version: '1.0.0',
    order: 26,
    tags: ['analyze', 'cross-artifact', 'audit', 'consistency', 'drift-detection', 'gap-analysis'],
    inputs: [
      { name: 'all_artifacts', type: 'artifact', required: true, description: 'All generated project artifacts' },
      { name: 'existing_codebase', type: 'codebase', required: false, description: 'Workspace code' },
    ],
    outputs: [
      { name: 'analysis_report', type: 'artifact', artifactName: 'analysis.md', description: 'Cross-artifact consistency report, identified gaps, drift warnings, and remediation actions', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Analyze (Cross-Artifact Engine)',
        nativeCapabilityId: 'speckit-analyze',
        specializationScore: 98,
        qualityScore: 97,
        strengths: ['Pioneered cross-artifact consistency analysis', 'Detects missing requirements in tasks.md', 'Flags undocumented architecture choices', 'Enforces strict bidirectional traceability'],
        weaknesses: ['None in cross-artifact analysis'],
        bestFor: ['SDD artifact verification', 'Preventing project drift', 'Pre-implementation audits'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Artifact Inspector',
        nativeCapabilityId: 'internal-analyze',
        specializationScore: 90,
        qualityScore: 91,
        strengths: ['Fast automated schema validation', 'Checklist item verification'],
        weaknesses: ['Less semantic depth than Spec Kit analyze'],
        bestFor: ['Fast CI artifact validation'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Multi-Lens Audit',
        nativeCapabilityId: 'bmad-analyze',
        specializationScore: 82,
        qualityScore: 85,
        strengths: ['High-level narrative consistency'],
        weaknesses: ['Not designed around rigid SDD artifact pipeline'],
        bestFor: ['Narrative consistency checks'],
      },
    ],
  },
  {
    id: 'forge.review',
    name: 'review',
    displayName: 'Multi-Lens Code & Architecture Review',
    group: 'verification',
    description: 'Perform holistic code review evaluating correctness, performance, maintainability, typing, error boundaries, and idiomatic standards.',
    version: '1.0.0',
    order: 27,
    tags: ['review', 'code-review', 'multi-lens', 'quality', 'audit', 'bmad-review'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Code to review' },
      { name: 'specification', type: 'artifact', required: false, defaultArtifact: 'spec.md', description: 'Specification doc' },
    ],
    outputs: [
      { name: 'review_report', type: 'artifact', artifactName: 'review.md', description: 'Multi-lens review report with severity-ranked findings, code snippets, and patch suggestions', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'bmad',
        providerName: 'BMAD Multi-Lens Review (bmad-review)',
        nativeCapabilityId: 'bmad-review',
        specializationScore: 98,
        qualityScore: 97,
        strengths: ['Industry gold-standard multi-lens review methodology', 'Parallel specialized reviewer personas (Architect, Security, QA, Maintainer, Perf)', 'Actionable diff suggestions with rationale', 'Prevents bike-shedding'],
        weaknesses: ['Can generate extensive feedback on large repos'],
        bestFor: ['Pull request reviews', 'Critical architecture audits', 'Pre-release verification'],
      },
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Conformance Review',
        nativeCapabilityId: 'speckit-review',
        specializationScore: 80,
        qualityScore: 84,
        strengths: ['Direct verification against spec checklist'],
        weaknesses: ['Less specialized in deep multi-lens code architecture review'],
        bestFor: ['Spec compliance checking'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Internal Static Reviewer',
        nativeCapabilityId: 'internal-review',
        specializationScore: 86,
        qualityScore: 88,
        strengths: ['Fast linter and typing checks', 'Clean code suggestions'],
        weaknesses: ['Single lens review'],
        bestFor: ['Quick pre-commit reviews'],
      },
    ],
  },
  {
    id: 'forge.security-review',
    name: 'security',
    displayName: 'Security Audit & Vulnerability Assessment',
    group: 'verification',
    description: 'Inspect code and dependencies for OWASP vulnerabilities, injection vectors, hardcoded secrets, unsafe deserialization, and auth bypasses.',
    version: '1.0.0',
    order: 28,
    tags: ['security', 'security-review', 'vulnerability', 'owasp', 'audit', 'cve', 'sast'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Codebase' },
      { name: 'threat_model', type: 'artifact', required: false, defaultArtifact: 'threat-model.md', description: 'Threat model doc' },
    ],
    outputs: [
      { name: 'security_audit_report', type: 'artifact', artifactName: 'security-audit.md', description: 'Security audit report with CVE severity ratings, remediation patches, and SAST findings', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Security SAST Engine',
        nativeCapabilityId: 'internal-security-audit',
        specializationScore: 97,
        qualityScore: 96,
        strengths: ['Automated secret scanning heuristics', 'OWASP Top 10 rule matching', 'Supply chain & package dependency audits', 'Clear remediation code diffs'],
        weaknesses: ['None in security verification'],
        bestFor: ['Security-critical audits', 'CI security gates', 'Secret scanning'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Security Lens Review',
        nativeCapabilityId: 'bmad-security-lens',
        specializationScore: 90,
        qualityScore: 91,
        strengths: ['Identifies systemic authorization/authentication flaws in architecture'],
        weaknesses: ['Less focused on static secret/package scanning'],
        bestFor: ['Auth architecture & trust boundary review'],
      },
    ],
  },
  {
    id: 'forge.performance-review',
    name: 'performance',
    displayName: 'Performance Profiling & Bottleneck Analysis',
    group: 'verification',
    description: 'Analyze time/space complexity, database query N+1 issues, memory leaks, event-loop blocking, and network payload sizes.',
    version: '1.0.0',
    order: 29,
    tags: ['performance', 'optimization', 'profiling', 'memory-leaks', 'n-plus-1', 'latency'],
    inputs: [
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Codebase' },
    ],
    outputs: [
      { name: 'perf_report', type: 'artifact', artifactName: 'performance-report.md', description: 'Performance bottleneck report with algorithmic complexity ratings and optimization recommendations', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Performance Profiler',
        nativeCapabilityId: 'internal-perf',
        specializationScore: 93,
        qualityScore: 92,
        strengths: ['Identifies N+1 query patterns', 'Event-loop blocking warnings', 'Bundle size optimization', 'Memory leak detection in JS/TS'],
        weaknesses: ['Static analysis based'],
        bestFor: ['Web/API optimization and bundle tuning'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Performance Architecture Review',
        nativeCapabilityId: 'bmad-perf-lens',
        specializationScore: 89,
        qualityScore: 90,
        strengths: ['Distributed caching and throughput analysis'],
        weaknesses: ['Less focused on micro-optimizations'],
        bestFor: ['High-throughput distributed systems'],
      },
    ],
  },
  {
    id: 'forge.conformance',
    name: 'conformance',
    displayName: 'Standards & Constitution Conformance',
    group: 'verification',
    description: 'Audit code and artifacts against non-negotiable constitution invariants and corporate compliance standards.',
    version: '1.0.0',
    order: 30,
    tags: ['conformance', 'compliance', 'standards', 'constitution-check'],
    inputs: [
      { name: 'constitution', type: 'artifact', required: true, defaultArtifact: 'constitution.md', description: 'Project constitution' },
      { name: 'existing_codebase', type: 'codebase', required: true, description: 'Codebase' },
    ],
    outputs: [
      { name: 'conformance_report', type: 'artifact', artifactName: 'conformance-report.md', description: 'Constitution invariant compliance matrix and violation log', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Constitution Guard',
        nativeCapabilityId: 'speckit-conformance',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['Rigorous invariant checking against constitution.md', 'Clear pass/fail gate statuses'],
        weaknesses: ['Requires constitution.md artifact'],
        bestFor: ['SDD governance compliance'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Invariant Validator',
        nativeCapabilityId: 'internal-conformance',
        specializationScore: 90,
        qualityScore: 91,
        strengths: ['Checks linter rules, file structure, and licensing'],
        weaknesses: ['Standard rules'],
        bestFor: ['Codebase hygiene checks'],
      },
    ],
  },

  // ==========================================
  // 7. DELIVERY GROUP
  // ==========================================
  {
    id: 'forge.converge',
    name: 'converge',
    displayName: 'Convergence & Residual Work Alignment',
    group: 'delivery',
    description: 'Evaluate remaining unchecked tasks, open checklist items, test failures, and synthesize convergence plan to reach release readiness.',
    version: '1.0.0',
    order: 31,
    tags: ['converge', 'residual-work', 'readiness', 'polish', 'burndown'],
    inputs: [
      { name: 'tasks', type: 'artifact', required: true, defaultArtifact: 'tasks.md', description: 'Tasks breakdown' },
      { name: 'checklist', type: 'artifact', required: false, defaultArtifact: 'checklist.md', description: 'Quality checklist' },
      { name: 'test_report', type: 'artifact', required: false, defaultArtifact: 'test-report.md', description: 'Test report' },
    ],
    outputs: [
      { name: 'convergence_doc', type: 'artifact', artifactName: 'convergence.md', description: 'Residual burndown plan, unresolved edge cases, and readiness certification', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'speckit',
        providerName: 'Spec Kit Converge Engine',
        nativeCapabilityId: 'speckit-converge',
        specializationScore: 98,
        qualityScore: 97,
        strengths: ['Pioneered the converge capability in SDLC', 'Systematic burndown of open tasks.md checkboxes', 'Guarantees zero forgotten acceptance criteria', 'Final polish roadmap'],
        weaknesses: ['None in convergence domain'],
        bestFor: ['Pre-release convergence', 'Sprint completion', 'Zero-defect delivery'],
      },
      {
        providerId: 'internal',
        providerName: 'Forge Readiness Assessor',
        nativeCapabilityId: 'internal-converge',
        specializationScore: 88,
        qualityScore: 89,
        strengths: ['Fast checkbox parsing and summary'],
        weaknesses: ['Less strategic than Spec Kit converge'],
        bestFor: ['Quick task status burndown'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Release Readiness Check',
        nativeCapabilityId: 'bmad-converge',
        specializationScore: 82,
        qualityScore: 85,
        strengths: ['Holistic risk review'],
        weaknesses: ['Not centered on markdown checklist burndown'],
        bestFor: ['Enterprise release risk analysis'],
      },
    ],
  },
  {
    id: 'forge.release',
    name: 'release',
    displayName: 'Release Packaging & Semantic Versioning',
    group: 'delivery',
    description: 'Generate changelogs, bump semantic versions, prepare release notes, and tag commits.',
    version: '1.0.0',
    order: 32,
    tags: ['release', 'semver', 'changelog', 'release-notes', 'tagging'],
    inputs: [
      { name: 'git_history', type: 'codebase', required: true, description: 'Git commits and changes' },
      { name: 'spec', type: 'artifact', required: false, defaultArtifact: 'spec.md', description: 'Specification doc' },
    ],
    outputs: [
      { name: 'changelog', type: 'artifact', artifactName: 'CHANGELOG.md', description: 'KeepAChangelog formatted release notes', format: 'markdown' },
      { name: 'release_notes', type: 'artifact', artifactName: 'RELEASE_NOTES.md', description: 'User-facing release highlights', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Release Manager',
        nativeCapabilityId: 'internal-release',
        specializationScore: 96,
        qualityScore: 95,
        strengths: ['Conventional commits parsing', 'Automated SemVer calculation', 'GitHub Release notes formatting', 'KeepAChangelog structure'],
        weaknesses: ['Requires conventional commit messages for optimal grouping'],
        bestFor: ['npm / PyPI / GitHub releases', 'Automated release pipelines'],
      },
      {
        providerId: 'bmad',
        providerName: 'BMAD Product Release Summarizer',
        nativeCapabilityId: 'bmad-release',
        specializationScore: 85,
        qualityScore: 88,
        strengths: ['Rich narrative product release summaries'],
        weaknesses: ['Less automated SemVer tooling'],
        bestFor: ['Product-focused marketing release notes'],
      },
    ],
  },
  {
    id: 'forge.deploy',
    name: 'deploy',
    displayName: 'Deployment & Release Orchestration',
    group: 'delivery',
    description: 'Execute build pipelines, deploy containers/serverless functions, update DNS/CDN, and run smoke tests.',
    version: '1.0.0',
    order: 33,
    tags: ['deploy', 'cd', 'smoke-test', 'production', 'staging'],
    inputs: [
      { name: 'configuration', type: 'configuration', required: true, description: 'Target environment configuration' },
    ],
    outputs: [
      { name: 'deployment_log', type: 'artifact', artifactName: 'deployment-log.md', description: 'Deployment execution logs and health check results', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Deployment Orchestrator',
        nativeCapabilityId: 'internal-deploy',
        specializationScore: 95,
        qualityScore: 94,
        strengths: ['Zero-downtime deployment strategies', 'Automated smoke testing', 'Health check monitoring'],
        weaknesses: ['Requires CI/CD environment integration'],
        bestFor: ['Automated deployments', 'Staging/Production pushes'],
      },
    ],
  },
  {
    id: 'forge.rollback',
    name: 'rollback',
    displayName: 'Emergency Rollback & Incident Recovery',
    group: 'delivery',
    description: 'Revert broken releases, trigger database migration rollbacks, restore previous stable states, and generate post-mortem logs.',
    version: '1.0.0',
    order: 34,
    tags: ['rollback', 'incident-response', 'revert', 'disaster-recovery'],
    inputs: [
      { name: 'deployment_log', type: 'artifact', required: true, defaultArtifact: 'deployment-log.md', description: 'Failed deployment details' },
    ],
    outputs: [
      { name: 'post_mortem', type: 'artifact', artifactName: 'post-mortem.md', description: 'Incident post-mortem, timeline, and remediation plan', format: 'markdown' },
    ],
    providers: [
      {
        providerId: 'internal',
        providerName: 'Forge Safe Rollback Engine',
        nativeCapabilityId: 'internal-rollback',
        specializationScore: 97,
        qualityScore: 96,
        strengths: ['Automated previous artifact restoration', 'Safe DB schema rollback steps', 'Blameless post-mortem template'],
        weaknesses: ['None in rollback domain'],
        bestFor: ['Incident recovery', 'Automated failover'],
      },
    ],
  },
];

/**
 * Capability Lookup Helper
 */
export function getCapabilityById(id: string): CapabilityManifest | undefined {
  let normalized = id.toLowerCase().trim().replace(/^forge\./, '');
  if (normalized === 'brd' || normalized === 'business-analysis') {
    normalized = 'business-requirements';
  } else if (normalized === 'tasks' || normalized === 'task') {
    normalized = 'tasks';
  } else if (normalized === 'security') {
    normalized = 'security';
  }

  return CAPABILITY_CATALOG.find(
    (c) => c.id.toLowerCase() === `forge.${normalized}` ||
           c.id.toLowerCase() === normalized ||
           c.name.toLowerCase() === normalized ||
           c.tags.includes(normalized)
  );
}

/**
 * Get capabilities grouped by SDLC Group
 */
export function getCapabilitiesByGroup(): Record<string, CapabilityManifest[]> {
  const groups: Record<string, CapabilityManifest[]> = {
    discovery: [],
    specification: [],
    architecture: [],
    planning: [],
    implementation: [],
    verification: [],
    delivery: [],
  };

  for (const cap of CAPABILITY_CATALOG) {
    if (groups[cap.group]) {
      groups[cap.group].push(cap);
    }
  }

  return groups;
}
